name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

permissions: {}

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/ruff-action@v3
        with:
          args: check custom_components/

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install dependencies
        run: pip install ".[test]"

      - name: Run tests
        run: pytest tests/
